services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - event
    environment:
      - PORT=3000
      - JWT_SECRET=dev-secret
      - AUTH_SERVICE_URL=http://auth:3001
      - EVENT_SERVICE_URL=http://event:3002

  auth:
    build: ./auth
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/auth
      - JWT_SECRET=dev-secret
      - JWT_EXPIRES_IN=1h
      - SALT_ROUNDS=10

  event:
    build: ./event
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      - PORT=3002
      - MONGO_URI=mongodb://mongo:27017/event

volumes:
  mongo_data:
